package com.millie.financemanager.service;

import com.millie.financemanager.dto.ExpenseRequestDto;
import com.millie.financemanager.entity.Category;
import com.millie.financemanager.entity.Expense;
import com.millie.financemanager.exception.NotFoundException;
import com.millie.financemanager.repository.CategoryRepository;
import com.millie.financemanager.repository.ExpenseRepository;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import static com.millie.financemanager.enums.PaymentType.CREDIT;
import static com.millie.financemanager.enums.Status.UNPAID;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class ExpenseServiceTest {

    @Mock
    private ExpenseRepository expenseRepository;

    @Mock
    private CategoryRepository categoryRepository;

    @InjectMocks
    private ExpenseService expenseService;

    @Test
    void shouldReturnExistingExpenses() {

        Expense expense = new Expense();
        expense.setId(1L);
        List<Expense> expensesList = new ArrayList<>();

        expensesList.add(expense);

        when(expenseRepository.findAll()).thenReturn(expensesList);

        List<Expense> result = expenseService.getExpenses();

        Assertions.assertEquals(1, result.toArray().length );

    }

    @Test
    void shouldReturnExpenseById() {

        Expense expense = new Expense();
        expense.setId(1L);

        when(expenseRepository.findById(1L)).thenReturn(Optional.of(expense));

        Expense result = expenseService.getExpenseById(1L);

        Assertions.assertEquals(1L, result.getId());

    }

    @Test
    void shouldThrowWhenExpenseNotFound() {

        Assertions.assertThrows(NotFoundException.class, () -> expenseService.getExpenseById(1L));

    }

    @Test
    void shouldReturnCreatedExpense() {

        ExpenseRequestDto requestDto = new ExpenseRequestDto();
        requestDto.setPaymentType(CREDIT);
        requestDto.setTotalValue(new BigDecimal("3500.00"));
        requestDto.setNumberOfInstallments(12);

        when(expenseRepository.save(any(Expense.class))).thenAnswer(invocation -> invocation.getArgument(0));

        Expense result = expenseService.createExpense(requestDto);

        Assertions.assertEquals(new BigDecimal("291.67"), result.getInstallment().getFirst().getInstallmentValue());
        Assertions.assertEquals(new BigDecimal("291.66"), result.getInstallment().getLast().getInstallmentValue());

        for (int i = 0; i < result.getInstallment().toArray().length; i++) {
            Assertions.assertEquals(UNPAID, result.getInstallment().get(i).getStatus());
            Assertions.assertEquals(i+1, result.getInstallment().get(i).getInstallmentNumber());
            Assertions.assertEquals(result, result.getInstallment().get(i).getExpense());
        }

    }

    @Test
    void shouldReturnExpenseWithValidCategory() {

        ExpenseRequestDto requestDto = new ExpenseRequestDto();
        requestDto.setCategoryId(1L);
        requestDto.setNumberOfInstallments(2);
        requestDto.setPaymentType(CREDIT);
        requestDto.setTotalValue(new BigDecimal("100.00"));

        Category category = new Category();
        category.setId(2L);

        when(categoryRepository.findById(1L)).thenReturn(Optional.of(category));
        when(expenseRepository.save(any(Expense.class))).thenAnswer(invocation -> invocation.getArgument(0));

        Expense result = expenseService.createExpense(requestDto);

        Assertions.assertEquals(category, result.getCategory());
    }

    @Test
    void shouldThrowNotFoundIfExpenseHasInvalidCategory() {

        ExpenseRequestDto requestDto = new ExpenseRequestDto();
        requestDto.setCategoryId(1L);
        requestDto.setNumberOfInstallments(2);
        requestDto.setPaymentType(CREDIT);
        requestDto.setTotalValue(new BigDecimal("100.00"));

        when(categoryRepository.findById(1L)).thenReturn(Optional.empty());

        Assertions.assertThrows(NotFoundException.class, () -> expenseService.createExpense(requestDto));

    }

    @Test
    void shouldReturnExpenseWithValidAutoGeneratedDueDate() {

        ExpenseRequestDto requestDto = new ExpenseRequestDto();
        requestDto.setNumberOfInstallments(2);
        requestDto.setPaymentType(CREDIT);
        requestDto.setTotalValue(new BigDecimal("100.00"));

        when(expenseRepository.save(any(Expense.class))).thenAnswer(invocation -> invocation.getArgument(0));

        Expense result = expenseService.createExpense(requestDto);

        Assertions.assertEquals(LocalDate.now(), result.getInstallment().getFirst().getDueDate());
    }

    @Test
    void shouldReturnExpenseWithInformedDueDate() {

        LocalDate firstDueDate = LocalDate.of(2030, 10, 6);

        ExpenseRequestDto requestDto = new ExpenseRequestDto();
        requestDto.setNumberOfInstallments(2);
        requestDto.setPaymentType(CREDIT);
        requestDto.setFirstDueDate(firstDueDate);
        requestDto.setTotalValue(new BigDecimal("100.00"));

        when(expenseRepository.save(any(Expense.class))).thenAnswer(invocation -> invocation.getArgument(0));

        Expense result = expenseService.createExpense(requestDto);

        Assertions.assertEquals(firstDueDate, result.getInstallment().getFirst().getDueDate());
    }

    @Test
    void shouldSuccessfullyDeleteExpense() {

        expenseRepository.deleteById(1L);
        Mockito.verify(expenseRepository).deleteById(1L);

    }
}
